PUT http://localhost:3000/contacts/6457195c5740ff3361e09c59 HTTP/1.1
Content-Type: application/json

{
    "birthday": "10/10/2000",
    "email": "johndoe@example.com",
    "favColor": "yellow",
    "firstName": "John",
    "lastName": "Doe"
}